version: '3.7'

services:

  frontend:
    image: portfolio-image:latest
    build: 
      context: ./
      dockerfile: Dockerfile
    ports: 
     - 3000:3000
    volumes:
      - ./:/app/frontend

